services:
  - type: web
    name: roma-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --forwarded-allow-ips="*" src.api.main:app
    envVars:
      - key: DEEPL_API_KEY
        sync: false
      - key: PORT
        value: "8000"
